### PR TITLE
Add a JSF example featuring WebJars

### PR DESCRIPTION
**Pull request by tsabirgaliev**
Here is a basic JSF application, where JSF components are skinned using
Foundation styles pulled through WebJars

### CODE REVIEW

**Comment by kubamarchwicki** [comment]
Where is the actual test? Automatic test?
Like in this example: https://github.com/javaee-samples/javaee7-samples/tree/master/servlet/resource-packaging - I though the aim of this project was to show JavaEE7 capabilities through automated tests.

**Comment by arun-gupta** [comment]
Couple of purposes ...

- Show the usage of Java EE 7 technologies
- How to test them in container agnostic manner

First one is well served here. Open another issue to add test?

**Comment by tsabirgaliev** [comment]
will be happy to implement tests, please give some directions what they should be like.  This demo only aims to show one doesn't always need rich/prime/whatever faces to have slick web ui with JSF.  No business logic behind it

**Comment by tsabirgaliev** [comment]
May we just merge this one with original servlet resource example, and check with webdriver that maven-pulled deps successfully provide resources? WDYT?

**Pull request merged**
