### PR TITLE
Fix some failures using wildfly-swarm profile

### PR DESCRIPTION
**Pull request by juangon**
-->by upgrading upgrading arquillian and wildfly swarm version. Additionally, cut the dependency from test-utils to parent to avoid unwanted added dependencies

Here we go @arjantijms !

Thanks a lot!

### CODE REVIEW

**Comment by arjantijms** [comment]
Thanks! Looks great. I'll wait for travis to clear before merging, but looks okay!

**Comment by juangon** [comment]
Great. Your solution looks much better than mine and is the actual fix for the actual error. Thanks!

**Comment by juangon** [comment]
Oopps it fails as it tries to compile the project alone first. I think we unfortunately need to declare that variable in the test-utils project. Duplicate variable but will work...

**Comment by juangon** [comment]
Will update branch on Monday.

**Comment by juangon** [comment]
Can't believe, 5 hours to execute these tests and 3 still left :-0

**Comment by juangon** [comment]
@arjantijms ready to go!

**Comment by arjantijms** [comment]
>@arjantijms ready to go!

\o/

**Comment by juangon** [comment]
Thanks very much @arjantijms !

**Pull request merged**
