### PR TITLE
Upgrade Thorntail with JDK 11 support

### PR DESCRIPTION
**Pull request by juangon**

### CODE REVIEW

**Comment by juangon** [comment]
Hi @arjantijms it seems it was merged into my branch instead into master?

**Comment by arjantijms** [comment]
>Hi @arjantijms it seems it was merged into my branch instead into master?

That's right, I first merged master in (using the "update branch" feature of Github), so the tests are run against the latest integrated version ;)

**Comment by juangon** [comment]
Oh ok @arjantijms , I forgot to rebase master first :-(. BTW tests looks like didn't start

**Comment by arjantijms** [comment]
> Oh ok @arjantijms , I forgot to rebase master first :-(. BTW tests looks like didn't start

No worries there, tests did run and everything is fine. Thx!

**Pull request merged**
